### ISSUE TITLE
Attempts to claim a pet cause the new pet to disappear. Error in console.

### ISSUE THREAD

**Issue by KevinNovak** [MyPetORG/MyPet#1164]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.13.1 (git-Spigot-6b015b4-94b8708)

**MyPet Build/Version:**
MyPet-3.0-SNAPSHOT (Build #1265)

**Do you use the premium version? (this wont change anything for you)**
No

**What is the expected result?**
The wolf becomes my pet when I hit it with a Lead.

**What happens instead of that?**
The wolf disappears. The plugin still tells me the wolf is my pet. An error occurs in the console. The same error occurs whenever I attempt to call my pet.

**Error:**
Also found at: https://pastebin.com/jWznFTmq
`[11:12:16 WARN]: [MyPet] Task #102 for MyPet v3.0 generated an exception
java.lang.NullPointerException: null
        at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:514) ~[?:?]
        at de.Keyle.MyPet.listeners.EntityListener$2.callback(EntityListener.java:550) ~[?:?]
        at de.Keyle.MyPet.listeners.EntityListener$2.callback(EntityListener.java:543) ~[?:?]
        at de.Keyle.MyPet.api.repository.RepositoryCallback.run(RepositoryCallback.java:37) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]`

**Comment by KevinNovak** [comment]
I discovered a bit since posting. This error does not happen with a default config. I was able to narrow it down the the WorldGuard hook option in the config:
```yaml 
Hooks:
    Kingdoms: false
    Towny: false
    Heroes: false
    Factions: false
    WorldGuard: true # Errors occurs when false
````

Which fits the line the error was thrown from: https://github.com/xXKeyleXx/MyPet/blob/master/modules/Plugin/src/main/java/de/Keyle/MyPet/entity/MyPet.java#L514
