### ISSUE TITLE
Some players randomly lost pet levels and pets

### ISSUE THREAD

**Issue by andris155** [MyPetORG/MyPet#1369]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_A clear and concise description of what the bug is._
Some players randomly lost pet levels and pets

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

I don't know. Randomly. Maybe the server restart cause this or maybe damaged database (?)

## Expected behavior

_A clear and concise description of what you expected to happen._

No lost pet levels and pets

## Actual behaviour

_If applicable, add screenshots to help explain your problem._
Lost some player pets and pet levels

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.
[ticket.zip](https://github.com/xXKeyleXx/MyPet/files/4496425/ticket.zip)

**Bukkit/Spigot/Bungee Build/Version:** Paper build 193 1.15.2

**MyPet Build/Version:** MyPet-3.10-SNAPSHOT-b#29

**What is the expected result?** No lost pet levels and pets

**What happens instead of that?** Lost some player pets and pet levels

**Error:**
```
commented

**Comment by andris155** [comment]
```
[22:59:49 INFO]: wolfhunter60 issued server command: /pch
[22:59:49 WARN]: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT] Abort due to constraint violation (UNIQUE constraint failed: players.name)
[22:59:49 WARN]: at org.sqlite.core.DB.newSQLException(DB.java:941)
[22:59:49 WARN]: at org.sqlite.core.DB.newSQLException(DB.java:953)
[22:59:49 WARN]: at org.sqlite.core.DB.execute(DB.java:854)
[22:59:49 WARN]: at org.sqlite.core.DB.executeUpdate(DB.java:895)
[22:59:49 WARN]: at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102)
[22:59:49 WARN]: at de.Keyle.MyPet.repository.types.SqLiteRepository$14.run(SqLiteRepository.java:954)
[22:59:49 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[22:59:49 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[22:59:49 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:59:49 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[22:59:49 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[22:59:49 WARN]: at java.base/java.lang.Thread.run(Unknown Source
```

**Comment by jumakituno** [comment]
https://youtu.be/OzVB_QXhpn8
