### ISSUE TITLE
Plugin doesn work

### ISSUE THREAD

**Issue by korozuroz** [MyPetORG/MyPet#1426]
11-03-2020 06:30 [INFO] [MyPet] Error-Reporter ENABLED
11-03-2020 06:31 [INFO] [MyPet] Enabling MyPet v3.11
11-03-2020 06:31 [INFO] [MyPet] No Update available.
11-03-2020 06:31 [WARNING] [MyPet] This version of MyPet is not compatible with "v1_16_R3". Is MyPet up to date?
11-03-2020 06:36 [INFO] [MyPet] Error-Reporter ENABLED
11-03-2020 06:36 [INFO] [MyPet] Enabling MyPet v3.11
11-03-2020 06:36 [INFO] [MyPet] No Update available.
11-03-2020 06:36 [WARNING] [MyPet] This version of MyPet is not compatible with "v1_16_R3". Is MyPet up to date?

**Comment by ClayCoffee** [comment]
[15:53:09 ERROR]: Error occurred while enabling MyPet v3.11 (Is it up to date?)
java.lang.NoSuchMethodError: net.minecraft.server.v1_16_R2.EntityLiving.cK()Lnet/minecraft/server/v1_16_R2/AttributeProvider$Builder;
        at de.Keyle.MyPet.compat.v1_16_R2.entity.MyAttributeDefaults.<clinit>(MyAttributeDefaults.java:33) ~[?:?]
        at de.Keyle.MyPet.compat.v1_16_R2.entity.EntityRegistry.registerDefaultAttributes(EntityRegistry.java:64) ~[?:?]
        at de.Keyle.MyPet.compat.v1_16_R2.entity.EntityRegistry.registerEntityType(EntityRegistry.java:58) ~[?:?]
        at de.Keyle.MyPet.compat.v1_16_R2.entity.EntityRegistry.registerEntity(EntityRegistry.java:73) ~[?:?]
        at de.Keyle.MyPet.compat.v1_16_R2.entity.EntityRegistry.registerEntityTypes(EntityRegistry.java:113) ~[?:?]
        at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:192) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Paper-1.16.4-b257.jar:git-Paper-257]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[Paper-1.16.4-b257.jar:git-Paper-257]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[Paper-1.16.4-b257.jar:git-Paper-257]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[Paper-1.16.4-b257.jar:git-Paper-257]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[Paper-1.16.4-b257.jar:git-Paper-257]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[Paper-1.16.4-b257.jar:git-Paper-257]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:239) ~[Paper-1.16.4-b257.jar:git-Paper-257]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[Paper-1.16.4-b257.jar:git-Paper-257]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[Paper-1.16.4-b257.jar:git-Paper-257]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

**Comment by niqoar** [comment]
Use dev build: https://mypet-plugin.de/download

**Comment by xXKeyleXx** [comment]
try the latest dev build!

**Comment by UserDerezzed** [comment]
This issue is resolved.
