### ISSUE TITLE
An error message is caused when bringing a pet into plotworld

### ISSUE THREAD

**Issue by shuiqing2046** [MyPetORG/MyPet#1468]
English is not my mother tongue. I am very sorry if I do not express myself clearly.

MyPet-3.11-SNAPSHOT-B1639

An error message is caused when bringing a pet into plotworld.

`[03:49:22 ERROR]: Could not pass event CreatureSpawnEvent to PlotSquared v5.13.11
java.lang.NullPointerException: null
        at com.sk89q.worldedit.bukkit.adapter.IBukkitAdapter.adapt(IBukkitAdapter.java:337) ~[?:?]
        at com.sk89q.worldedit.bukkit.adapter.IDelegateBukkitImplAdapter.adapt(IDelegateBukkitImplAdapter.java:262) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:338) ~[?:?]
        at com.plotsquared.bukkit.util.BukkitEntityUtil.checkEntity(BukkitEntityUtil.java:329) ~[?:?]
        at com.plotsquared.bukkit.listener.EntityEventListener.creatureSpawnEvent(EntityEventListener.java:179) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor76.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-675]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-675]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-675]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-675]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:719) ~[patched_1.16.5.jar:git-Paper-675]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:637) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.WorldServer.addEntity0(WorldServer.java:1302) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.WorldServer.addEntity(WorldServer.java:1203) ~[patched_1.16.5.jar:git-Paper-675]
        at de.Keyle.MyPet.compat.v1_16_R3.entity.EntityRegistry.spawnMinecraftEntity(EntityRegistry.java:101) ~[?:?]
        at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:546) ~[?:?]
        at de.Keyle.MyPet.listeners.PlayerListener$4.run(PlayerListener.java:425) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-675]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1424) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1127) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-675]
        at java.lang.Thread.run(Unknown Source) [?:?]`

**Comment by Jakllp** [comment]
Should be fixed with 3.12-SNAPSHOT-B1674
See https://github.com/MyPetORG/MyPet/commit/ab6759f05c1f802b784c7164e4c5cb4e68c28e8e
