### ISSUE TITLE
Task #x for Mypet 3.1x generated an exception

### ISSUE THREAD

**Issue by 08edu02** [MyPetORG/MyPet#1485]
# Bugreport

I have checked other issues to make sure this is not a duplicate.

## Describe the bug

In the client side it says "An internal error occurred while attempting to perform this command" when i try to use /petc or /petcall,

## To Reproduce

1.  Tame a pet (tried with a pig and a silverfish)
2. Use the command /petc or /petcall

## Expected behavior

The pet should came to the client.

## Actual behaviour

"An internal error occurred while attempting to perform this command." in the client side and: "Task #x for Mypet v.311(also tested in 3.10) generated an exception." in the server console.

**Bukkit/Spigot/Bungee Build/Version:**

1.12.2 magma forge 2855

**MyPet Build/Version:**

3.10 and 3.11

**What is the expected result?**

The command should work

**What happens instead of that?**

**Error:**

![unknown](https://user-images.githubusercontent.com/86580343/132239986-a82ae3a5-105b-46a0-87c4-2ff7a7cd7789.png)
 
[ticket.zip](https://github.com/scomans/MyPet/files/7116910/ticket.zip)

It appears a error.

PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
Task #9 for MyPet v3.11 generated an exception
 java.lang.AbstractMethodError: Method de/Keyle/MyPet/compat/v1_12_R1/entity/types/EntityMySilverfish.getUniqueID()Ljava/util/UUID; is abstract
        at de.Keyle.MyPet.compat.v1_12_R1.entity.types.EntityMySilverfish.getUniqueID(EntityMySilverfish.java) ~[MyPet-3.11-SNAPSHOT-B1642.jar:?]
        at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:501) ~[MyPet-3.11-SNAPSHOT-B1642.jar:?]
        at de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:481) ~[MyPet-3.11-SNAPSHOT-B1642.jar:?]
        at de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62) ~[MyPet-3.11-SNAPSHOT-B1642.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:65) ~[CraftTask.class:dd991e7-DEV]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:429)

**Comment by Jakllp** [comment]
Please try the 3.12-Snapshot
Should be fixed in there

**Comment by Jakllp** [comment]
Isn't the same error anymore but something different

**Comment by scomans** [comment]
Also it's a forge/non spigot thing. So not supported anyways. Way to hard to deal with.

**Comment by 08edu02** [comment]
Ok, so... Should I try with only a spigot server and test it? Will be a fix in a future? Thx for the replies.

**Comment by Jakllp** [comment]
It should work on spigot

**Comment by 08edu02** [comment]
Ok so should I have to wait for the fix or can I help in any way?
