### ISSUE TITLE
Can't open /petshop even with /op

### ISSUE THREAD

**Issue by Zhekev** [MyPetORG/MyPet#1488]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_A clear and concise description of what the bug is._

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. type /petshop in chat
2.not petshop won't pop up
...

## Expected behavior

_A clear and concise description of what you expected to happen._

## Actual behaviour

_If applicable, add screenshots to help explain your problem._
![image](https://user-images.githubusercontent.com/90779224/133451222-d646d339-8396-4366-afb9-20e0673f7d01.png)

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.
[ticket.zip](https://github.com/MyPetORG/MyPet/files/7170806/ticket.zip)

**Bukkit/Spigot/Bungee Build/Version:**
Spigot
**MyPet Build/Version:**
MyPet-3.12-SNAPSHOT-B1643
**What is the expected result?**
opening /petshop or /petsh
**What happens instead of that?**
A message pop up as "you are not allow to use this!"
**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```

**Comment by Jakllp** [comment]
Out of your console-log:
```
[08:57:41] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
[08:57:41] [Server thread/WARN]:  in 'string', line 235, column 9:
[08:57:41] [Server thread/WARN]:             Price:950
[08:57:41] [Server thread/WARN]:             ^
[08:57:41] [Server thread/WARN]: could not find expected ':'
[08:57:41] [Server thread/WARN]:  in 'string', line 236, column 7:
[08:57:41] [Server thread/WARN]:           sheep:
[08:57:41] [Server thread/WARN]:           ^
[08:57:41] [Server thread/WARN]: 
[08:57:41] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59)
[08:57:41] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[08:57:41] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
[08:57:41] [Server thread/WARN]: 	at de.Keyle.MyPet.util.shop.ShopManager.onEnable(ShopManager.java:57)
[08:57:41] [Server thread/WARN]: 	at de.Keyle.MyPet.api.util.service.ServiceManager.activate(ServiceManager.java:89)
[08:57:41] [Server thread/WARN]: 	at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:426)
[08:57:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[08:57:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[08:57:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[08:57:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:511)
[08:57:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:425)
[08:57:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:619)
[08:57:41] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266)
[08:57:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010)
[08:57:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
[08:57:41] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[08:57:41] [Server thread/WARN]: Caused by: while scanning a simple key
[08:57:41] [Server thread/WARN]:  in 'string', line 235, column 9:
[08:57:41] [Server thread/WARN]:             Price:950
[08:57:41] [Server thread/WARN]:             ^
[08:57:41] [Server thread/WARN]: could not find expected ':'
[08:57:41] [Server thread/WARN]:  in 'string', line 236, column 7:
[08:57:41] [Server thread/WARN]:           sheep:
[08:57:41] [Server thread/WARN]:           ^
[08:57:41] [Server thread/WARN]: 
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:484)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:299)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:247)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:602)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:221)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:191)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:146)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
[08:57:41] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:416)
[08:57:41] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[08:57:41] [Server thread/WARN]: 	... 15 more
```

If we now take a look at your pet-shops.yml and the sheep-section as the log suggests:
The price looks like this:
`price:950` but it needs a space: `price: 950`

Could you change that and try again?
