### ISSUE TITLE
Crash with Spigot 1.18.1

### ISSUE THREAD

**Issue by schufti** [MyPetORG/MyPet#1513]
## Describe the bug

If the pet start to follow me i get a crash and the server stops

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. You pet is beside you
2. Move 25 steps and the crash comes
...

## Expected behavior

The pet comes to me

## Actual behaviour

Client is closing and the server stops
## Additional context

**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.18.1  ( with Spigot 1.18 no problem )

**MyPet Build/Version:**
MyPet-3.12-SNAPSHOT-B1660

**Error:**
```
[12:26:06] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1313) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1206) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1034) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.world.entity.ai.navigation.NavigationAbstract.o()'
	at de.Keyle.MyPet.compat.v1_18_R1.entity.ai.navigation.VanillaNavigation.stop(VanillaNavigation.java:53) ~[?:?]
	at de.Keyle.MyPet.compat.v1_18_R1.entity.ai.movement.FollowOwner.finish(FollowOwner.java:101) ~[?:?]
	at de.Keyle.MyPet.api.entity.ai.AIGoalSelector.tick(AIGoalSelector.java:136) ~[?:?]
	at de.Keyle.MyPet.compat.v1_18_R1.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:1190) ~[?:?]
	at de.Keyle.MyPet.compat.v1_18_R1.entity.EntityMyPet.w_(EntityMyPet.java:1064) ~[?:?]
	at net.minecraft.world.entity.EntityLiving.k(EntityLiving.java:2808) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
	at net.minecraft.world.entity.EntityInsentient.k(EntityInsentient.java:383) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
	at de.Keyle.MyPet.compat.v1_18_R1.entity.EntityMyPet.k(EntityMyPet.java:1398) ~[?:?]
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:801) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
	at net.minecraft.world.level.World.a(World.java:702) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
	at net.minecraft.server.level.WorldServer.lambda$9(WorldServer.java:398) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
	at net.minecraft.world.level.entity.EntityTickList.a(SourceFile:54) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:378) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1300) ~[spigot-1.18.1-R0.1-SNAPSHOT

P
```

**Comment by Jakllp** [comment]
B1660 is not yet compatible with 1.18.1 due to a dependency issue.
Please wait for the next build

**Comment by schufti** [comment]
Thank you for the fast answer. Best pet plugin ever

**Comment by schufti** [comment]
MyPet-3.12-SNAPSHOT-B1661 solve the issue with 1.18.1. Thank you
