### ISSUE TITLE
MyPet can't start in paperspigot 1.18.2 server.

### ISSUE THREAD

**Issue by smartmadio** [MyPetORG/MyPet#1532]
# Bug report

## Describe the bug

MyPet plugin can't be enabled in PaperSpigot 1.18.2 server.
```
[20:14:06] [Server thread/ERROR]: Error occurred while enabling MyPet v3.12 (Is it up to date?)
java.lang.IllegalStateException: This registry can't create intrusive holders
	at net.minecraft.core.MappedRegistry.createIntrusiveHolder(MappedRegistry.java:337) ~[?:?]
	at net.minecraft.world.entity.EntityType.<init>(EntityType.java:307) ~[?:?]
	at net.minecraft.world.entity.EntityType$Builder.build(EntityType.java:722) ~[?:?]
	at de.Keyle.MyPet.compat.v1_18_R2.entity.EntityRegistry.registerEntityType(EntityRegistry.java:61) ~[MyPet-3.12-SNAPSHOT-B1679.jar:?]
	at de.Keyle.MyPet.compat.v1_18_R2.entity.EntityRegistry.registerEntity(EntityRegistry.java:77) ~[MyPet-3.12-SNAPSHOT-B1679.jar:?]
	at de.Keyle.MyPet.compat.v1_18_R2.entity.EntityRegistry.registerEntityTypes(EntityRegistry.java:123) ~[MyPet-3.12-SNAPSHOT-B1679.jar:?]
	at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:192) ~[MyPet-3.12-SNAPSHOT-B1679.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-242]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-242]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-242]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-242]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-242]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1165) ~[paper-1.18.2.jar:git-Paper-242]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-242]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:14:06] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [mDisabling MyPet v3.12[m
```

## To Reproduce

1. Put MyPet-3.12-SNAPSHOT-B1679.jar to plugins folder
2. Start server.
...

## Expected behavior

Plugin could be used

## Actual behaviour

_If applicable, add screenshots to help explain your problem._

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:**
PaperSpigot 1.18.2

**MyPet Build/Version:**
MyPet-3.12-SNAPSHOT-B1679

**What is the expected result?**

**What happens instead of that?**

**Comment by Jakllp** [comment]
Are you using citizens?

**Comment by smartmadio** [comment]
Yes,I’m using citizens.

**Comment by Jakllp** [comment]
This isn't a MyPet-Issue but a Citizens one. Please update your Citizens to their newest release and it should work
