### ISSUE TITLE
Spigot 1.17

### ISSUE THREAD

**Issue by Ray-Plays-yt** [MyPetORG/MyPet#1542]
Latest Dev Build: 3.12-SNAPSHOT-B1683
Server Version: Spigot 1.17.R1

First load, on a clean server! Plugin isn't crashed, loaded successfully, with 1 error, then using the "/mypet" command getting this:
"An internal error occurred while attempting to perform this command"

(Something wrong while load the entity: bee)
Console Log:

[Server thread/ERROR]: Error occurred while enabling MyPet v3.12 (Is it up to date?)
java.lang.NoSuchMethodError: 'net.minecraft.world.entity.ai.attributes.AttributeProvider$Builder net.minecraft.world.entity.animal.EntityBee.fJ()'
        at de.Keyle.MyPet.compat.v1_17_R1.entity.MyAttributeDefaults.<clinit>(MyAttributeDefaults.java:113) ~[?:?]
        at de.Keyle.MyPet.compat.v1_17_R1.entity.EntityRegistry.registerDefaultAttributes(EntityRegistry.java:70) ~[?:?]
        at de.Keyle.MyPet.compat.v1_17_R1.entity.EntityRegistry.registerEntityType(EntityRegistry.java:64) ~[?:?]
        at de.Keyle.MyPet.compat.v1_17_R1.entity.EntityRegistry.registerEntity(EntityRegistry.java:78) ~[?:?]
        at de.Keyle.MyPet.compat.v1_17_R1.entity.EntityRegistry.registerEntityTypes(EntityRegistry.java:118) ~[?:?]
        at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:192) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at me.PCPSells.aplapis.PluginAPI.enablePlugin(PluginAPI.java:70) ~[?:?]
        at me.PCPSells.APLMain$3.run(APLMain.java:163) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1252) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1027) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3170-Spigot-a483d2c-ec116f6]
        at java.lang.Thread.run(Thread.java:831) [?:?]

PLS Fix it! Great Plugin!

**Comment by Jakllp** [comment]
1.17 is not supported by design.
1.17.1 is

**Comment by Jakllp** [comment]
There technically is this build that still works for 1.17 but it's not receiving updates anymore and is quite some builds behind

https://github.com/Jakllp/MyPet/releases/tag/3.12-1.17-SNAPSHOT
