### ISSUE TITLE
java.lang.NoSuchMethodError: 'net.minecraft.world.entity.ai.attributes.AttributeProvider$Builder

### ISSUE THREAD

**Issue by Gida4** [MyPetORG/MyPet#1564]
# Bug report

* [ ] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

When the server starts, the plugin disables itself.

## To Reproduce

At every server startup.

**Bukkit/Spigot/Bungee Build/Version:**
purpur-1.19.2-1752

**MyPet Build/Version:**
MyPet-3.12-SNAPSHOT-B1700

**Error:**
```
[17:13:34] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [.[0;32;22mMyPet.[m] .[mEnabling MyPet v3.12.[m
[17:13:34] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [.[0;32;22mMyPet.[m] .[mNo Update available..[m
[17:13:34] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [.[0;32;22mMyPet.[m] .[mCustom entity registry found: net.citizensnpcs.nms.v1_19_R1.util.CustomEntityRegistry.[m
[17:13:34] [Server thread/ERROR]: Error occurred while enabling MyPet v3.12 (Is it up to date?)
java.lang.NoSuchMethodError: 'net.minecraft.world.entity.ai.attributes.AttributeProvider$Builder net.minecraft.world.entity.decoration.EntityArmorStand.dB()'
        at de.Keyle.MyPet.compat.v1_19_R1.entity.MyAttributeDefaults.<clinit>(MyAttributeDefaults.java:55) ~[MyPet.jar:?]
        at de.Keyle.MyPet.compat.v1_19_R1.entity.EntityRegistry.registerDefaultAttributes(EntityRegistry.java:69) ~[MyPet.jar:?]
        at de.Keyle.MyPet.compat.v1_19_R1.entity.EntityRegistry.registerEntityType(EntityRegistry.java:63) ~[MyPet.jar:?]
        at de.Keyle.MyPet.compat.v1_19_R1.entity.EntityRegistry.registerEntity(EntityRegistry.java:77) ~[MyPet.jar:?]
        at de.Keyle.MyPet.compat.v1_19_R1.entity.EntityRegistry.registerEntityTypes(EntityRegistry.java:123) ~[MyPet.jar:?]
        at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:195) ~[MyPet.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:594) ~[purpur-1.19.2.jar:git-Purpur-1752]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:508) ~[purpur-1.19.2.jar:git-Purpur-1752]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1752]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1752]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.19.2.jar:git-Purpur-1752]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[purpur-1.19.2.jar:git-Purpur-1752]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1752]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:13:34] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [.[0;32;22mMyPet.[m] .[mDisabling MyPet v3.12.[m
```

**Comment by Jakllp** [comment]
1.19.2 is not supported yet
