### ISSUE TITLE
Update to 1.19.2

### ISSUE THREAD

**Issue by rochadvdgit** [MyPetORG/MyPet#1565]
[12:55:55 INFO]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Enabling MyPet v3.12
[12:55:55 ERROR]: Error occurred while enabling MyPet v3.12 (Is it up to date?)
java.lang.NoSuchMethodError: 'net.minecraft.world.entity.ai.attributes.AttributeProvider$Builder net.minecraft.world.entity.decoration.EntityArmorStand.dB()'
        at de.Keyle.MyPet.compat.v1_19_R1.entity.MyAttributeDefaults.<clinit>(MyAttributeDefaults.java:55) ~[MyPet-3.12-SNAPSHOT-B1700.jar:?]
        at de.Keyle.MyPet.compat.v1_19_R1.entity.EntityRegistry.registerDefaultAttributes(EntityRegistry.java:69) ~[MyPet-3.12-SNAPSHOT-B1700.jar:?]
        at de.Keyle.MyPet.compat.v1_19_R1.entity.EntityRegistry.registerEntityType(EntityRegistry.java:63) ~[MyPet-3.12-SNAPSHOT-B1700.jar:?]
        at de.Keyle.MyPet.compat.v1_19_R1.entity.EntityRegistry.registerEntity(EntityRegistry.java:77) ~[MyPet-3.12-SNAPSHOT-B1700.jar:?]
        at de.Keyle.MyPet.compat.v1_19_R1.entity.EntityRegistry.registerEntityTypes(EntityRegistry.java:123) ~[MyPet-3.12-SNAPSHOT-B1700.jar:?]
        at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:195) ~[MyPet-3.12-SNAPSHOT-B1700.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-123]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-123]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-123]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-123]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-123]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1125) ~[paper-1.19.2.jar:git-Paper-123]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-123]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:55:55 INFO]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Disabling MyPet v3.12

**Comment by Jakllp** [comment]
On vacation rn.
Will get to it at some point.

**Comment by Jakllp** [comment]
Done in `3.12-SNAPSHOT-B1701`
