### ISSUE TITLE
Pet doesn't spawn or show up (Magma 1.12.2)

### ISSUE THREAD

**Issue by CallmeDome** [MyPetORG/MyPet#1570]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

After I have bought a pet, using the petshop, it doesn't show up. Commands like /petcall doesn't work. It will produce the message "An internal error occurred while attempting to perform this command".

## To Reproduce

1. Install the plugin
2. Try to buy a pet

## Expected behavior

The pet should appear near the player and the command should lead to something

## Actual behaviour

"Internal error" and the pet doesn't appears.

## Additional context

**Bukkit/Spigot/Bungee Build/Version: Magma version 48ec0a1

**MyPet Build/Version: 3.10

**Error-log
[13:06:08] [Server thread/ERROR] [global]: TIMING_STACK_CORRUPTION - Report this to the plugin MyPet(Look for errors above this in the logs) (TimingIdentifier{id=MyPet:Task: de.Keyle.MyPet.api.util.Timer$$Lambda$1371/164077469 (interval:20)} did not stopTiming)
java.lang.Throwable: null
	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:113) [TimingHandler.class:48ec0a1]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:918) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[13:06:09] [Server thread/WARN] [de.Keyle.MyPet.MyPetPlugin]: [[0;32;22mMyPet[m] [m[0;31;1mTask #16 for MyPet v3.1 generated an exception[m
java.lang.AbstractMethodError: Method de/Keyle/MyPet/compat/v1_12_R1/entity/types/EntityMySheep.getUniqueID()Ljava/util/UUID; is abstract
	at de.Keyle.MyPet.compat.v1_12_R1.entity.types.EntityMySheep.getUniqueID(EntityMySheep.java) ~[?:?]
	at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:501) ~[?:?]
	at de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:481) ~[?:?]
	at de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:65) ~[CraftTask.class:48ec0a1]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:429) [CraftScheduler.class:48ec0a1]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:917) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312
[latest.log](https://github.com/MyPetORG/MyPet/files/9395564/latest.log)
]

**Comment by Jakllp** [comment]
Won't be fixed as this is due to Magma.
MyPet only supports Spigot and Paper
