### ISSUE TITLE
Error "this.compatUtil" is null

### ISSUE THREAD

**Issue by KiaraFlores** [MyPetORG/MyPet#1573]
Hi, in the console i see this error
Cannot invoke "de.Keyle.MyPet.api.util.CompatUtil.getInternalVersion()" because "this.compatUtil" is null
        at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:143) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:525) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:439) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:584) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:403) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:968) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
        at java.lang.Thread.run(Thread.java:833) [?:?]

how can i fix it?

**Comment by Jakllp** [comment]
Which version of MyPet are you using?

**Comment by KiaraFlores** [comment]
The most recent

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Jakl ***@***.***>
Enviado: Thursday, September 1, 2022 1:43:28 AM
Para: MyPetORG/MyPet ***@***.***>
CC: KiaraFlores ***@***.***>; Author ***@***.***>
Asunto: Re: [MyPetORG/MyPet] Error "this.compatUtil" is null (Issue #1573)


Which version of MyPet are you using?

**Comment by Jakllp** [comment]
3.10 or 3.12?

**Comment by KiaraFlores** [comment]
3.10

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Jakl ***@***.***>
Enviado: Thursday, September 1, 2022 1:47:02 AM
Para: MyPetORG/MyPet ***@***.***>
CC: KiaraFlores ***@***.***>; Author ***@***.***>
Asunto: Re: [MyPetORG/MyPet] Error "this.compatUtil" is null (Issue #1573)


3.10 or 3.12?

**Comment by Jakllp** [comment]
3.10 is not compatible with 1.19.2
Please use 3.12 from this page:
https://mypet-plugin.de/download

**Comment by KiaraFlores** [comment]
Thank u, I’m gonna try it tomorrow !!

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Jakl ***@***.***>
Enviado: Thursday, September 1, 2022 1:55:39 AM
Para: MyPetORG/MyPet ***@***.***>
CC: KiaraFlores ***@***.***>; Author ***@***.***>
Asunto: Re: [MyPetORG/MyPet] Error "this.compatUtil" is null (Issue #1573)


3.10 is not compatible with 1.19.2
Please use 3.12 from this page:
https://mypet-plugin.de/download
