### ISSUE TITLE
WorldGuard error

### ISSUE THREAD

**Issue by catches** [MyPetORG/MyPet#1583]
# Bug report

* [ ] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Got this WorldGuard error in console.

## To Reproduce

Happens relatively frequently when the pet teleports to you or switching between worlds.

1. 
2.
...

## Expected behavior

_A clear and concise description of what you expected to happen._

## Actual behaviour

_If applicable, add screenshots to help explain your problem._

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:** This server is running Pufferfish version git-Pufferfish-40 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: deb9638 on HEAD)
You are running 2 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Pufferfish-38 (MC: 1.19.2)  

**MyPet Build/Version:** 3.12-SNAPSHOT-B1725

**What is the expected result?**

**What happens instead of that?**

**Error:**
```
[16:13:53 ERROR]: Could not pass event CreatureSpawnEvent to WorldGuard v7.0.7+216b061
java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because the return value of "org.bukkit.entity.EntityType.getName()" is null
        at com.fastasyncworldedit.bukkit.adapter.IBukkitAdapter.adapt(IBukkitAdapter.java:346) ~[FastAsyncWorldEdit-Bukkit-2.4.9-SNAPSHOT-294.jar:?]
        at com.fastasyncworldedit.bukkit.adapter.IDelegateBukkitImplAdapter.adapt(IDelegateBukkitImplAdapter.java:271) ~[FastAsyncWorldEdit-Bukkit-2.4.9-SNAPSHOT-294.jar:?]
        at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:395) ~[FastAsyncWorldEdit-Bukkit-2.4.9-SNAPSHOT-294.jar:?]
        at com.sk89q.worldguard.bukkit.listener.WorldGuardEntityListener.onCreatureSpawn(WorldGuardEntityListener.java:623) ~[worldguard-bukkit-7.0.7-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor498.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:git-Pufferfish-40]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:740) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:645) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1492) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1400) ~[?:?]
        at de.Keyle.MyPet.compat.v1_19_R1_2.entity.EntityRegistry.spawnMinecraftEntity(EntityRegistry.java:114) ~[MyPet-3.12-SNAPSHOT-B1725.jar:?]
        at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:547) ~[MyPet-3.12-SNAPSHOT-B1725.jar:?]
        at de.Keyle.MyPet.listeners.PlayerListener$4.run(PlayerListener.java:427) ~[MyPet-3.12-SNAPSHOT-B1725.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1475) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1399) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
[ticket.zip](https://github.com/MyPetORG/MyPet/files/9904794/ticket.zip)

**Comment by Jakllp** [comment]
Quick question:
There probably is a hooks-config.yml in your MyPet-Folder, right?
If so:
Is the worldguard hook enabled in there?

**Comment by Jakllp** [comment]
Your ticket.zip says otherwise.
MyPet never hooks with Worldguard.

Can you send over your hooks-config.yml?

**Comment by Jakllp** [comment]
This is insanely weird...
Because as you can see:
The WorldGuard-Hook never gets enabled

```
10-31-2022 16:03 [INFO] [MyPet] Error-Reporter ENABLED
10-31-2022 16:04 [INFO] [MyPet] Enabling MyPet v3.12
10-31-2022 16:04 [INFO] [MyPet] No Update available.
10-31-2022 16:04 [INFO] [MyPet] Custom entity registry found: net.citizensnpcs.nms.v1_19_R1.util.CustomEntityRegistry
10-31-2022 16:04 [INFO] [MyPet] Compat mode for v1_19_R1 loaded.
10-31-2022 16:04 [INFO] [MyPet] Exp calculation mode: MyPet
10-31-2022 16:04 [INFO] [MyPet] Current Exp-Cache is invalid, it will be recalculated.
10-31-2022 16:04 [INFO] [MyPet] Loading WorldGroups...
10-31-2022 16:04 [INFO] [MyPet]    added world to 'default' group.
10-31-2022 16:04 [INFO] [MyPet]    added world_nether to 'default' group.
10-31-2022 16:04 [INFO] [MyPet]    added world_the_end to 'default' group.
10-31-2022 16:04 [INFO] [MyPet]    added Lobby to 'default' group.
10-31-2022 16:04 [INFO] [MyPet] Default skilltree files created.
10-31-2022 16:04 [INFO] [MyPet] Connect to SQLite database...
10-31-2022 16:04 [INFO] [MyPet] SQLite connection successful.
10-31-2022 16:04 [INFO] [MyPet] Citizens (2.0.30-SNAPSHOT (build 2742)) hook activated.
10-31-2022 16:04 [INFO] [MyPet] MythicMobs (5.1.4-3aa1b5d2) hook activated.
10-31-2022 16:04 [INFO] [MyPet] PlaceholderAPI (2.11.1) hook activated.
10-31-2022 16:04 [INFO] [MyPet] ProtocolLib (5.0.0-SNAPSHOT-b600) hook activated.
10-31-2022 16:04 [INFO] [MyPet] SuperVanish (6.2.10) hook activated.
10-31-2022 16:04 [INFO] [MyPet] Vault (1.7.3-b131) (Economy: EssentialsX Economy) (Permissions: LuckPerms) hook activated.
10-31-2022 16:04 [INFO] [MyPet] Version 3.12-SNAPSHOT-b1725 ENABLED
10-31-2022 16:13 [INFO] [MyPet] added test to 'default' group.
```

I mean - I can fix it in another way but it still is... Quite odd

**Comment by Jakllp** [comment]
Well you should also consider updating WorldGuard as 7.0.7 doesn't even support 1.19+ officially

**Comment by deHasher** [comment]
```
25.06 23:25:57 [Server] ERROR Could not pass event CreatureSpawnEvent to WorldGuard v7.0.5+3827266
25.06 23:25:57 [Server] INFO java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because the return value of "org.bukkit.entity.EntityType.getName()" is null
25.06 23:25:57 [Server] INFO at com.sk89q.worldedit.bukkit.adapter.IBukkitAdapter.adapt(IBukkitAdapter.java:337) ~[?:?]
25.06 23:25:57 [Server] INFO at com.sk89q.worldedit.bukkit.adapter.IDelegateBukkitImplAdapter.adapt(IDelegateBukkitImplAdapter.java:262) ~[?:?]
25.06 23:25:57 [Server] INFO at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:338) ~[?:?]
25.06 23:25:57 [Server] INFO at com.sk89q.worldguard.bukkit.listener.WorldGuardEntityListener.onCreatureSpawn(WorldGuardEntityListener.java:644) ~[?:?]
25.06 23:25:57 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor237.execute(Unknown Source) ~[?:?]
25.06 23:25:57 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1171]
25.06 23:25:57 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Purpur-1171]
25.06 23:25:57 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1171]
25.06 23:25:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1171]
25.06 23:25:57 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:734) ~[patched_1.16.5.jar:git-Purpur-1171]
25.06 23:25:57 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:652) ~[patched_1.16.5.jar:git-Purpur-1171]
25.06 23:25:57 [Server] INFO at net.minecraft.server.v1_16_R3.WorldServer.addEntity0(WorldServer.java:1906) ~[patched_1.16.5.jar:git-Purpur-1171]
25.06 23:25:57 [Server] INFO at net.minecraft.server.v1_16_R3.WorldServer.addEntity(WorldServer.java:1807) ~[patched_1.16.5.jar:git-Purpur-1171]
25.06 23:25:57 [Server] INFO at de.Keyle.MyPet.compat.v1_16_R3.entity.EntityRegistry.spawnMinecraftEntity(EntityRegistry.java:104) ~[?:?]
25.06 23:25:57 [Server] INFO at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:547) ~[?:?]
25.06 23:25:57 [Server] INFO at de.Keyle.MyPet.entity.MyPet.respawnPet(MyPet.java:597) ~[?:?]
25.06 23:25:57 [Server] INFO at de.Keyle.MyPet.entity.MyPet.schedule(MyPet.java:638) ~[?:?]
25.06 23:25:57 [Server] INFO at de.Keyle.MyPet.api.util.Timer.lambda$startTimer$0(Timer.java:52) ~[?:?]
25.06 23:25:57 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
25.06 23:25:57 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1171]
25.06 23:25:57 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1171]
25.06 23:25:57 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
25.06 23:25:57 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
25.06 23:25:57 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
25.06 23:25:57 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
25.06 23:25:57 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
```

Similar error...
Server: git-Purpur-1171 (MC: 1.16.5)
MyPet: 3.12-SNAPSHOT-B1741
WorldGuard: 7.0.5+3827266
FAWE: 1.16-710;f6af992 (only this version works on 1.16.5 more or less stably)
