### ISSUE TITLE
Add DeathMessages Support to MyPets

### ISSUE THREAD

**Issue by catches** [MyPetORG/MyPet#1584]
# Feature request

What part of MyPet needs this?
The plugin itself

## Is your feature request related to a problem? Please describe

Getting spammed this error
`[23:15:55 ERROR]: Could not pass event EntityDamageEvent to DeathMessages v1.4.15
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getSimpleName()" because the return value of "org.bukkit.entity.EntityType.getEntityClass()" is null
        at dev.mrshawn.deathmessages.listeners.EntityDamage.onEntityDamage(EntityDamage.java:38) ~[DeathMessages-1.4.15.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor963.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:git-Pufferfish-40]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:249) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1153) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1127) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:964) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1187) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2143) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1376) ~[?:?]
        at net.minecraft.world.entity.Entity.baseTick(Entity.java:857) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:392) ~[?:?]
        at net.minecraft.world.entity.Mob.baseTick(Mob.java:331) ~[?:?]
        at net.minecraft.world.entity.Entity.tick(Entity.java:804) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2955) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:404) ~[?:?]
        at de.Keyle.MyPet.compat.v1_19_R1_2.entity.EntityMyPet.k(EntityMyPet.java:1410) ~[MyPet-3.12-SNAPSHOT-B1725.jar:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1207) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:732) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:710) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1537) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1399) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-40]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

## Describe the solution you'd like

Support DeathMessages (https://github.com/Shawn11564/DeathMessages)

## Additional context

**Bukkit/Spigot/Bungee Build/Version:** This server is running Pufferfish version git-Pufferfish-40 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: deb9638 on HEAD)
You are running 2 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Pufferfish-38 (MC: 1.19.2)

**MyPet Build/Version:** 3.12-SNAPSHOT-B1725

**Comment by UserDerezzed** [comment]
Seems to be a dead project now, closing
