### ISSUE TITLE
Mypet disabled when Citizens2 is enabled

### ISSUE THREAD

**Issue by M1904** [MyPetORG/MyPet#1587]
# Bug report

if u want to use Citizens, your MyPet disable.

## Describe the bug

I tried to start my paper server with 1.19.3 and all the latest updates but got the error below. After removing Citizens2 from my plugin list, MyPet worked. However, I need both plugins. Do you see what's wrong and can you fix it?

**Bukkit/Spigot/Bungee Build/Version:**
Paper 1.19.3-328

**MyPet Build/Version:**
3.12-SNAPSHOT-B1729

**What is the expected result?**
Works with citizens2 (we actually use Citizens-2.0.30-b2813)

**Error:**
```
[13:15:08 INFO]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Enabling MyPet v3.12
[13:15:08 INFO]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] No Update available.
[13:15:08 INFO]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Custom entity registry found: net.citizensnpcs.nms.v1_19_R2.util.CustomEntityRegistry
[13:15:08 ERROR]: Error occurred while enabling MyPet v3.12 (Is it up to date?)
java.lang.IllegalStateException: This registry can't create intrusive holders
        at net.minecraft.core.MappedRegistry.createIntrusiveHolder(MappedRegistry.java:369) ~[?:?]
        at net.minecraft.world.entity.EntityType.<init>(EntityType.java:327) ~[?:?]
        at net.minecraft.world.entity.EntityType.<init>(EntityType.java:319) ~[?:?]
        at net.minecraft.world.entity.EntityType$Builder.build(EntityType.java:783) ~[?:?]
        at de.Keyle.MyPet.compat.v1_19_R2.entity.EntityRegistry.registerEntityType(EntityRegistry.java:65) ~[MyPet-3.12-SNAPSHOT-B1729.jar:?]
        at de.Keyle.MyPet.compat.v1_19_R2.entity.EntityRegistry.registerEntity(EntityRegistry.java:85) ~[MyPet-3.12-SNAPSHOT-B1729.jar:?]
        at de.Keyle.MyPet.compat.v1_19_R2.entity.EntityRegistry.registerEntityTypes(EntityRegistry.java:131) ~[MyPet-3.12-SNAPSHOT-B1729.jar:?]
        at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:195) ~[MyPet-3.12-SNAPSHOT-B1729.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578) ~[paper-1.19.3.jar:git-Paper-328]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492) ~[paper-1.19.3.jar:git-Paper-328]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-328]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-328]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:301) ~[paper-1.19.3.jar:git-Paper-328]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-328]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-328]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:15:08 INFO]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Disabling MyPet v3.12
```

**Comment by Jakllp** [comment]
This is a citizens issue.
I provided them with a "solution" (see the mentioned issue)

You'll need to wait for them to update their plugin. I'll leave this issue open until then

**Comment by M1904** [comment]
ich danke dir :)

**Comment by Jakllp** [comment]
They implemented the fix - dev build [2814](https://ci.citizensnpcs.co/job/Citizens2/2814/)
