### ISSUE TITLE
Bug on Magmafoundation

### ISSUE THREAD

**Issue by GravityhQ** [MyPetORG/MyPet#1594]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

The Bug is that Mypet ist not loading on the Magmafoundation

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. Install Server on Magmafoundation [ Its a Server client for Forge  + Spigot ]
2. Install Mypet

## Expected behavior

I tried to use commands of Mypet but nothing happens. For example i tried to use /petinfo and i tried to claim a Pet.

## Actual behaviour

https://i.imgur.com/tBBjLCF.png - This is the Only response i get when trying to use Commands
Claiming Pets doesent work

## Additional context

> Cant use the /petadmin command --> Nothing happens

**Bukkit/Spigot/Bungee Build/Version:**
Magma Version 1.18.2

**MyPet Build/Version:**
Newest Version MyPet-3.12-SNAPSHOT-B1734

**What is the expected result?**

**What happens instead of that?**

**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES

[ERROR] .... [Minecraft/]: Error occurred while enabling MyPet v3.12 (Is it up to date?)

java.lang.IllegalStateException: Registry is already frozen

at net.minecraftforge.registries.NamespacedHolderHelper.createIntrusiveHolder(NamespacedHolderHelper.java:177) ~[forge-1.18.2-40.2.0-universal.jar%2355!/:?] {re:classloading}

at net.minecraftforge.registries.NamespacedDefaultedWrapper.createIntrusiveHolder(NamespacedDefaultedWrapper.java:205) ~[forge-1.18.2-40.2.0-universal.jar%2355!/:?] {re:classloading}

at net.minecraftforge.registries.NamespacedDefaultedWrapper.m_203693_(NamespacedDefaultedWrapper.java:33) ~[forge-1.18.2-40.2.0-universal.jar%2355!/:?] {re:classloading}

at net.minecraft.world.entity.EntityType.<init>(EntityType.java:155) ~[server-1.18.2-20220404.173914-srg.jar%2350!/:?] {re:classloading}

at net.minecraft.world.entity.EntityType$Builder.m_20712_(EntityType.java:746) ~[server-1.18.2-20220404.173914-srg.jar%2350!/:?] {re:classloading}

at de.Keyle.MyPet.compat.v1_18_R2.entity.EntityRegistry.registerEntityType(EntityRegistry.java:65) ~[?:?] {}

at de.Keyle.MyPet.compat.v1_18_R2.entity.EntityRegistry.registerEntity(EntityRegistry.java:85) ~[?:?] {}

at de.Keyle.MyPet.compat.v1_18_R2.entity.EntityRegistry.registerEntityTypes(EntityRegistry.java:141) ~[?:?] {}

**Comment by Jakllp** [comment]
Expected as MyPet has to dig really deep to register its entities.

MyPet is only supposed to support Spigot/Paper

**Comment by GravityhQ** [comment]
I know that mypet is only working on Spigot/Paper. I am running a hybrid Server on Forge and Spigot. My Server can use Forge mods and Spigot plugins at the same time. I dont unterstand why mypet isnt working.  There are currently 23 Spigot plugins and 32 Forge mods working perfectly fine together on my server.

**Comment by Jakllp** [comment]
As long as mypet didn't say "Custom Entity Registry found" before that, then the following happened:

MyPet needs to register new EntityTypes within the Minecrafr Vanilla Internal Registries. So not something provided by Spigot, but by the normal Minecraft Server. This is, what it is trying to do right there.  
The problem is, that those registries need to be unfrozen. The fields that need be adjusted to unfreeze the registries aren't visible so their obfuscated names are hardcoded into mypet (obfuscated: the field name could legit be "f" for one version of minecraft and then "g" for the next one).

Forge might have changed those field names. Or, because there are now multiple APIs on top of Vanilla, the entire registry-system might have been changed (many mods have custom mobs so I expect there to be a layer on top of the entity registry/it to he changed by forge)

Result: 
It would need a rewrite of the entity registry system to support such Hybrids like Magmafusion. For basically every hybrid (bc as far as I know they all have different variants of dealing with the internal registries)

**Comment by Jakllp** [comment]
It might also be a simple incompatibility with an old citizens version, but that is something I could only find out if you shared the entire mypet startup log (there should be a few more lines just above the error)

**Comment by GravityhQ** [comment]
Thank you for the answer now i understand it. Maybe you can read something out of the error if not its still fine.

Here is the Startup code

[ERROR] .... [Minecraft/]: Error occurred while enabling MyPet v3.12 (Is it up to date?)

java.lang.IllegalStateException: Registry is already frozen

at net.minecraftforge.registries.NamespacedHolderHelper.createIntrusiveHolder(NamespacedHolderHelper.java:177) ~[forge-1.18.2-40.2.0-universal.jar%2355!/:?] {re:classloading}

at net.minecraftforge.registries.NamespacedDefaultedWrapper.createIntrusiveHolder(NamespacedDefaultedWrapper.java:205) ~[forge-1.18.2-40.2.0-universal.jar%2355!/:?] {re:classloading}

at net.minecraftforge.registries.NamespacedDefaultedWrapper.m_203693_(NamespacedDefaultedWrapper.java:33) ~[forge-1.18.2-40.2.0-universal.jar%2355!/:?] {re:classloading}

at net.minecraft.world.entity.EntityType.<init>(EntityType.java:155) ~[server-1.18.2-20220404.173914-srg.jar%2350!/:?] {re:classloading}

at net.minecraft.world.entity.EntityType$Builder.m_20712_(EntityType.java:746) ~[server-1.18.2-20220404.173914-srg.jar%2350!/:?] {re:classloading}

at de.Keyle.MyPet.compat.v1_18_R2.entity.EntityRegistry.registerEntityType(EntityRegistry.java:65) ~[?:?] {}

at de.Keyle.MyPet.compat.v1_18_R2.entity.EntityRegistry.registerEntity(EntityRegistry.java:85) ~[?:?] {}

at de.Keyle.MyPet.compat.v1_18_R2.entity.EntityRegistry.registerEntityTypes(EntityRegistry.java:141) ~[?:?] {}

at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:195) ~[?:?] {}

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[forge-1.18.2-40.2.0-universal.jar%2355!/:?] {re:mixin,re:classloading,re:mixin,re:mixin}

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:415) ~[forge-1.18.2-40.2.0-universal.jar%2355!/:?] {re:classloading}

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge-1.18.2-40.2.0-universal.jar%2355!/:?] {re:classloading}

at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:468) ~[forge-1.18.2-40.2.0-universal.jar%2355!/:7e29f765-296df566-9fb885e8] {re:classloading,re:mixin}

at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:348) ~[forge-1.18.2-40.2.0-universal.jar%2355!/:7e29f765-296df566-9fb885e8] {re:classloading,re:mixin}

at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:447) ~[server-1.18.2-20220404.173914-srg.jar%2350!/:?] {re:classloading,pl:accesstransformer:B}

at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:358) ~[server-1.18.2-20220404.173914-srg.jar%2350!/:?] {re:classloading,pl:accesstransformer:B}

at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:252) ~[server-1.18.2-20220404.173914-srg.jar%2350!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}

at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:841) ~[server-1.18.2-20220404.173914-srg.jar%2350!/:?] {re:classloading,pl:accesstransformer:B}

at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:257) ~[server-1.18.2-20220404.173914-srg.jar%2350!/:?] {re:classloading,pl:accesstransformer:B}

at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin,re:mixin,re:mixin}
