### ISSUE TITLE
Circular Dependencies Issues

### ISSUE THREAD

**Issue by mercurialmusic** [MyPetORG/MyPet#1601]
# Bug report

* [X] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

MyPet dependencies creating circular dependency problem in Paper builds after 404 causing crash. Running a test server without MyPet (as well as Jobs) solved the crash problems. This seemed to affect several plugins, hence the Jobs inclusion. I tested with both plugins together and independently -- the crash occurs even with just MyPet. Using the legacy loader flag is not a viable option since it causes other problems.
https://gist.github.com/mercurialmusic/c36845b12e60ba14d49d46487d69d00d

**Bukkit/Spigot/Bungee Build/Version:** git-Paper-424 (MC: 1.19.3)
**MyPet Build/Version:** MyPet-3.12-B1737.jar

**Comment by Jakllp** [comment]
They really opened a can of worms with this one...

**Comment by mercurialmusic** [comment]
> They really opened a can of worms with this one...

Yeahhhh. And no transition/warning/communication. It's been a mess. Thanks for looking into it!

**Comment by Jakllp** [comment]
If you need a fix right now:
You could go into the jar (with something like winrar) and edit plugin.yml - just deleting all softdepends (except for maybe protocollib) should do the trick

**Comment by mercurialmusic** [comment]
> If you need a fix right now: You could go into the jar (with something like winrar) and edit plugin.yml - just deleting all softdepends (except for maybe protocollib) should do the trick

Thanks for the tip! I'm sitting pretty on b404 for now since there are a couple other plugins with the same, but might need to use that come 1.19.4 if the rest don't update by then.

**Comment by mercurialmusic** [comment]
May be resolved with builds after Paper 425 per this message on their Discord: https://discord.com/channels/289587909051416579/976631292747735080/1079722792557228102

Will leave this issue at your discretion but at least I'm able to start my servers on the latest Paper builds now. I'll let you know if I notice any weirdness otherwise.

Thanks!

**Comment by mercurialmusic** [comment]
Nevermind. It's back again in the latest, but only showed up for MyPet. -_- I did the dependencies thing in plugin.yml, removing Residence for now, which seems to be working so far.

**Comment by Jakllp** [comment]
I tried creating a circular dependency on the newest paper version and it didn't crash

And they didn't add it back (at least not according to their changelogs) so...
Can you recheck?

**Comment by mercurialmusic** [comment]
Yup, confirming it still crashes at least on git-Paper-448 (MC: 1.19.3) because of MyPet's dependency on Residence (which we don't really use that dependency anyway). Removing that from the plugin.yml allows it to work. Error below:
```
[17:25:18] [ServerMain/INFO]: Building unoptimized datafixer
[17:25:19] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:25:20] [ServerMain/INFO]: Loaded 7 recipes
[17:25:20] [Server thread/INFO]: Starting minecraft server version 1.19.3
[17:25:20] [Server thread/INFO]: Loading properties
[17:25:20] [Server thread/INFO]: This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)
[17:25:20] [Server thread/INFO]: Server Ping Player Sample Count: 12
[17:25:20] [Server thread/INFO]: Using 4 threads for Netty based IO
[17:25:20] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[17:25:20] [Server thread/INFO]: Default game type: SURVIVAL
[17:25:20] [Server thread/INFO]: Generating keypair
[17:25:21] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:30008
[17:25:21] [Server thread/INFO]: Using epoll channel type
[17:25:21] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[17:25:21] [Server thread/INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[17:25:21] [Server thread/ERROR]: [io.papermc.paper.plugin.storage.SimpleProviderStorage] Circular plugin loading detected!
[17:25:21] [Server thread/ERROR]: [io.papermc.paper.plugin.storage.SimpleProviderStorage] Circular load order:
[17:25:21] [Server thread/ERROR]: [io.papermc.paper.plugin.storage.SimpleProviderStorage]   Residence -> CMI -> Jobs -> MyPet -> Residence
[17:25:21] [Server thread/ERROR]: [io.papermc.paper.plugin.storage.SimpleProviderStorage] Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help.
[17:25:21] [Server thread/ERROR]: [io.papermc.paper.plugin.storage.SimpleProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true
[17:25:21] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Circular plugin loading from plugins Residence
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.handleCycle(SimpleProviderStorage.java:70) ~[paper-1.19.3.jar:git-Paper-448]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.19.3.jar:git-Paper-448]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.3.jar:git-Paper-448]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:428) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:25:21] [Server thread/ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2023-03-17_17.25.21-server.txt
[17:25:21] [Server thread/INFO]: Stopping server
[17:25:21] [Server thread/INFO]: Saving players
[17:25:21] [Server thread/INFO]: Saving worlds
[17:25:21] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[17:25:21] [Server thread/INFO]: Flushing Chunk IO
[17:25:21] [Server thread/INFO]: Closing Thread Pool
[17:25:21] [Server thread/INFO]: Closing Server
```

**Comment by Jakllp** [comment]
Done
Published in https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1738
