### ISSUE TITLE
/petcall doesn't work on latest beta release

### ISSUE THREAD

**Issue by mastercake10** [MyPetORG/MyPet#1640]
Running [3.12-SNAPSHOT-B1745 ](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1745) gives the following error after calling a pet (`/petcall`, sheep):
```yml
[20:29:52 WARN]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Task #16 for MyPet v3.12 generated an exception
java.lang.NullPointerException: field is marked non-null but is null
        at de.Keyle.MyPet.api.util.ReflectionUtil.setFieldValue(ReflectionUtil.java:89) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.compat.v1_20_R1.entity.CraftMyPet.<init>(CraftMyPet.java:59) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.compat.v1_20_R1.entity.EntityMyPet.getBukkitEntity(EntityMyPet.java:466) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.compat.v1_20_R1.entity.EntityMyPet.getBukkitEntity(EntityMyPet.java:109) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:480) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:487) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.jar:git-Paper-17]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.jar:git-Paper-17]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.jar:git-Paper-17]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

```
> version
[20:32:32 INFO]: Checking version, please wait...
[20:32:33 INFO]: This server is running Paper version git-Paper-17 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: c287e92)
```

However, this issue doesn't seem to exist in  [3.12-SNAPSHOT-B1741](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1741).

**Comment by mastercake10** [comment]
Issue seems to be gone on latest paper
```
> version
[20:46:24 INFO]: Checking version, please wait...
[20:46:24 INFO]: This server is running Paper version git-Paper-127 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 6520ca1)
You are running the latest version
Previous version: git-Paper-17 (MC: 1.20)
```

**Comment by Jakllp** [comment]
Yep. MyPet had to adapt to changes made in the newest Spigot release (which were adopted by Paper etc) which is why the newest build doesn't work on older versions of 1.20 Spigot/Paper etc anymore
