### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by catches** [MyPetORG/MyPet#1641]
Error on startup
```
[00:47:44 INFO]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Enabling MyPet v3.12
[00:47:44 INFO]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Custom entity registry found: net.citizensnpcs.nms.v1_20_R1.util.CustomEntityRegistry
[00:47:44 ERROR]: Error occurred while enabling MyPet v3.12 (Is it up to date?)
java.lang.RuntimeException: failed to load a class
        at de.Keyle.MyPet.api.util.ReflectionUtil.getClass(ReflectionUtil.java:47) ~[MyPet-3.12-SNAPSHOT-B1741.jar:?]
        at de.Keyle.MyPet.compat.v1_20_R1.entity.EntityRegistry.registerEntity(EntityRegistry.java:83) ~[MyPet-3.12-SNAPSHOT-B1741.jar:?]
        at de.Keyle.MyPet.compat.v1_20_R1.entity.EntityRegistry.registerEntityTypes(EntityRegistry.java:143) ~[MyPet-3.12-SNAPSHOT-B1741.jar:?]
        at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:195) ~[MyPet-3.12-SNAPSHOT-B1741.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[pufferfish-1.20.1.jar:git-Pufferfish-22]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.1.jar:git-Pufferfish-22]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[pufferfish-1.20.1.jar:git-Pufferfish-22]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[pufferfish-1.20.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[pufferfish-1.20.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[pufferfish-1.20.1.jar:git-Pufferfish-22]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[pufferfish-1.20.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1103) ~[pufferfish-1.20.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.1.jar:git-Pufferfish-22]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IncompatibleClassChangeError: class de.Keyle.MyPet.compat.v1_20_R1.entity.CraftMyPet overrides final method org.bukkit.craftbukkit.v1_20_R1.entity.CraftEntity.getType()Lorg/bukkit/entity/EntityType;
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:232) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:157) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at de.Keyle.MyPet.api.util.ReflectionUtil.getClass(ReflectionUtil.java:45) ~[MyPet-3.12-SNAPSHOT-B1741.jar:?]
        ... 15 more
[00:47:44 INFO]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Disabling MyPet v3.12
```

**Comment by Jakllp** [comment]
Already fixed in the newest build of MyPet.
