### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by ChibeMeliodas** [MyPetORG/MyPet#1644]
[09:38:13 WARN]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Task #225 for MyPet v3.12 generated an exception
java.lang.NullPointerException: field is marked non-null but is null
        at de.Keyle.MyPet.api.util.ReflectionUtil.setFieldValue(ReflectionUtil.java:89) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.compat.v1_20_R1.entity.CraftMyPet.<init>(CraftMyPet.java:59) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.compat.v1_20_R1.entity.EntityMyPet.getBukkitEntity(EntityMyPet.java:466) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.compat.v1_20_R1.entity.EntityMyPet.getBukkitEntity(EntityMyPet.java:109) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:480) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:487) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-117]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-117]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:38:14 WARN]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Task #225 for MyPet v3.12 generated an exception
java.lang.NullPointerException: field is marked non-null but is null
        at de.Keyle.MyPet.api.util.ReflectionUtil.setFieldValue(ReflectionUtil.java:89) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.compat.v1_20_R1.entity.CraftMyPet.<init>(CraftMyPet.java:59) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.compat.v1_20_R1.entity.EntityMyPet.getBukkitEntity(EntityMyPet.java:466) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.compat.v1_20_R1.entity.EntityMyPet.getBukkitEntity(EntityMyPet.java:109) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:480) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:487) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-117]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-117]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:38:15 WARN]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Task #225 for MyPet v3.12 generated an exception
java.lang.NullPointerException: field is marked non-null but is null
        at de.Keyle.MyPet.api.util.ReflectionUtil.setFieldValue(ReflectionUtil.java:89) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.compat.v1_20_R1.entity.CraftMyPet.<init>(CraftMyPet.java:59) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.compat.v1_20_R1.entity.EntityMyPet.getBukkitEntity(EntityMyPet.java:466) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.compat.v1_20_R1.entity.EntityMyPet.getBukkitEntity(EntityMyPet.java:109) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:480) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:487) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62) ~[MyPet-3.12-SNAPSHOT-B1745.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-117]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-117]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-117]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Jakllp** [comment]
Update your Paper.

If this didn't fix it, please feel free to reopen this issue
