### ISSUE TITLE
Cant call pet

### ISSUE THREAD

**Issue by bry1231** [MyPetORG/MyPet#1645]
When I install this plugin, its work,but if I buy a pet, then it will spam this in console:
[03:51:17] [Server thread/WARN]: [MyPet] Task #63 for MyPet v3.12 generated an exception
java.lang.NullPointerException: field is marked non-null but is null
        at de.Keyle.MyPet.api.util.ReflectionUtil.setFieldValue(ReflectionUtil.java:89) ~[?:?]
        at de.Keyle.MyPet.compat.v1_20_R1.entity.CraftMyPet.<init>(CraftMyPet.java:59) ~[?:?]
        at de.Keyle.MyPet.compat.v1_20_R1.entity.EntityMyPet.getBukkitEntity(EntityMyPet.java:466) ~[?:?]
        at de.Keyle.MyPet.compat.v1_20_R1.entity.EntityMyPet.getBukkitEntity(EntityMyPet.java:109) ~[?:?]
        at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:480) ~[?:?]
        at de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:487) ~[?:?]
        at de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1257) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3844-Spigot-b41c46d-c335a55]

And if I type /petcall ingame, it will say:
An internal error occurred while attempting to perform this command

but any else command are works.

**Comment by bry1231** [comment]
And if I type /petcall ingame, it will say:
An internal error occurred while attempting to perform this command

**Comment by Jakllp** [comment]
Update your Spigot.

**Comment by bry1231** [comment]
> 更新您的 Spigot。
> 
> 如果这不能解决您的问题，请随时重新打开此问题。

My spigot version is MinecraftJE-Spigot-1.20.1, isn't it good?

**Comment by Jakllp** [comment]
The problem is that midway through 1.20.1 they changed internal code and mypet needed to adapt.

Think of it like MyPet build numbers:
Spigot has older 1.20.1 builds and newer ones.
And the newest mypet builds only work with the new spigot builds.
So even tho it still is 1.20.1 it is not the same as newer 1.20.1 builds

**Comment by bry1231** [comment]
> The problem is that midway through 1.20.1 they changed internal code and mypet needed to adapt.
> 
> Think of it like MyPet build numbers: Spigot has older 1.20.1 builds and newer ones. And the newest mypet builds only work with the new spigot builds. So even tho it still is 1.20.1 it is not the same as newer 1.20.1 builds
> 
> So you basically have to update your 1.20.1 to newer 1.20.1 xD

OMG it really works XD, thank you so much!!
