### ISSUE TITLE
[MyPet] Task #42 for MyPet v3.12 generated an exception java.lang.IllegalArgumentException: null

### ISSUE THREAD

**Issue by Kaijunoki** [MyPetORG/MyPet#1652]
# Bug report

* [yep ] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

[MyPet] Task #42 for MyPet v3.12 generated an exception
java.lang.IllegalArgumentException: null

## To Reproduce
1.
2.
...

## Expected behavior

_A clear and concise description of what you expected to happen._

## Actual behaviour

_If applicable, add screenshots to help explain your problem._

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version: purpur-1.20.4-2124**

**MyPet Build/Version: MyPet-3.12-SNAPSHOT-B1755**

**What is the expected result?: Don't get this warning**

**What happens instead of that?: lag**

**Error:**
```
[22:18:04] [Server thread/WARN]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Task #42 for MyPet v3.12 generated an exception
java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:129) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntityType.minecraftToBukkit(CraftEntityType.java:18) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.<init>(CraftEntity.java:83) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.<init>(CraftLivingEntity.java:90) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftMob.<init>(CraftMob.java:17) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at de.Keyle.MyPet.compat.v1_20_R3.entity.CraftMyPet.<init>(CraftMyPet.java:54) ~[MyPet-3.12-SNAPSHOT-B1755.jar:?]
	at de.Keyle.MyPet.compat.v1_20_R3.entity.EntityMyPet.getBukkitEntity(EntityMyPet.java:468) ~[MyPet-3.12-SNAPSHOT-B1755.jar:?]
	at de.Keyle.MyPet.compat.v1_20_R3.entity.EntityMyPet.getBukkitEntity(EntityMyPet.java:109) ~[MyPet-3.12-SNAPSHOT-B1755.jar:?]
	at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:477) ~[MyPet-3.12-SNAPSHOT-B1755.jar:?]
	at de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:487) ~[MyPet-3.12-SNAPSHOT-B1755.jar:?]
	at de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62) ~[MyPet-3.12-SNAPSHOT-B1755.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1666) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1545) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2124]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
```

**Comment by Jakllp** [comment]
As dumb as this sounds:  
Can you try restarting your server?
I've had the same issue when I first started the plugin on 1.20.4 but never had it ever since.

**Comment by Jakllp** [comment]
Any update?
