### ISSUE TITLE
Compatibility issues with plugin elitemobs

### ISSUE THREAD

**Issue by kelegele** [MyPetORG/MyPet#1661]
# Bug report

* [✅ ] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

**Compatibility issues with plugin elitemobs**（https://www.spigotmc.org/resources/%E2%9A%94elitemobs%E2%9A%94.40090/）
When I install both of these plugins on the server, my player pet (MyPet) often clears the Elite Mobs when they touch each other (not killing), and an error message will appear in the background

## To Reproduce

1. Install  elitemobs and mypet on a server
2. Players carry pets to fight against elite monsters
3. My pet has a certain probability (not 100%) of clearing elite mobs directly

## Expected behavior

My pet kills elite monsters just like killing original monsters

## Actual behaviour

MyPet clears the EliteMobs without killing，and console error message:

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.
[ticket.zip](https://github.com/MyPetORG/MyPet/files/14973682/ticket.zip)

**Bukkit/Spigot/Bungee Build/Version:**
Paper version git-Paper-435 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)

**MyPet Build/Version:**
MyPet-3.12

**Error:**
```
[11:22:08 ERROR]: Entity threw exception at em_adventurers_guild:220.51319925093213,71.0,276.99267320501394
java.lang.ClassCastException: class de.Keyle.MyPet.compat.v1_20_R3.entity.types.EntityMyChicken cannot be cast to class net.minecraft.world.entity.Display$BlockDisplay (de.Keyle.MyPet.compat.v1_20_R3.entity.types.EntityMyChicken is in unnamed module of loader 'MyPet-3.12-SNAPSHOT-B1756.jar' @4e5f3687; net.minecraft.world.entity.Display$BlockDisplay is in unnamed module of loader java.net.URLClassLoader @25f38edc)
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.getEntity(CraftEntity.java:107) ~[paper-1.20.4.jar:git-Paper-435]
        at net.minecraft.world.entity.Entity.getBukkitEntity(Entity.java:255) ~[paper-1.20.4.jar:git-Paper-435]
        at net.minecraft.world.entity.LivingEntity.getBukkitLivingEntity(LivingEntity.java:263) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.knockback(LivingEntity.java:1933) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1552) ~[?:?]
        at net.minecraft.world.entity.Mob.doHurtTarget(Mob.java:1688) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.doHurtTarget(Zombie.java:365) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.checkAndPerformAttack(MeleeAttackGoal.java:129) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.tick(MeleeAttackGoal.java:121) ~[?:?]
        at net.minecraft.world.entity.ai.goal.ZombieAttackGoal.tick(ZombieAttackGoal.java:28) ~[?:?]
        at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:63) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:154) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:145) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:926) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3417) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:676) ~[?:?]
        at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:45) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.aiStep(Zombie.java:270) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3066) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:438) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:240) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1409) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1309) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:916) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.4.jar:git-Paper-435]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:896) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1714) ~[paper-1.20.4.jar:git-Paper-435]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-435]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1515) ~[paper-1.20.4.jar:git-Paper-435]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[paper-1.20.4.jar:git-Paper-435]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-435]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by Jakllp** [comment]
It looks like you are running MyPet 3.12 b1756  
I hate to be this guy but can you try updating?  
I believe that this problem should be fixed in b1757 (https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1757)  

Keep me updated on wether or not this solves the issue

**Comment by kelegele** [comment]
这段时间没发现这个问题了，应该是解决了，感谢🙇‍

I haven't found this problem in this period of time. It should be solved. Thank you.
