### ISSUE TITLE
Failed to handle packet net.minecraft.network.protocol.game.PacketPlayInUseEntity@

### ISSUE THREAD

**Issue by Bali0531** [MyPetORG/MyPet#1662]
# Bug report

* [x]  I have checked other issues to make sure this is not a duplicate.

## Describe the bug

An error message is spamming in the console.

## To Reproduce

-
...

## Expected behavior

-

## Actual behaviour

-
## Additional context

> [ticket.zip](https://github.com/MyPetORG/MyPet/files/15214266/ticket.zip)

**Bukkit/Spigot/Bungee Build/Version:**

1.20.4 purpur 2176

**MyPet Build/Version:**
v3.12-B1755
**What is the expected result?**
-
**What happens instead of that?**
-
**Error:**
```
[21:40:42] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.PacketPlayInUseEntity@6a3faf22, suppressing error
java.lang.Cla
ssCastException: class de.Keyle.MyPet.compat.v1_20_R3.entity.types.EntityMyIllusioner cannot be cast to class net.minecraft.world.entity.Display$BlockDisplay (de.Keyle.MyPet.compat.v1_20_R3.entity.types.EntityMyIllusioner is in unnamed module of loader 'MyPet-3.12-SNAPSHOT-B1755.jar' @ef9dbaf; net.minecraft.world.entity.Display$BlockDisplay is in unnamed module of loader java.net.URLClassLoader @22927a81)
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.getEntity(CraftEntity.java:122) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.world.entity.Entity.getBukkitEntity(Entity.java:255) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.world.entity.LivingEntity.getBukkitLivingEntity(LivingEntity.java:263) ~[?:?]
...
```

**Comment by Jakllp** [comment]
Update MyPet.
