### ISSUE TITLE
EntityMyAllay error

### ISSUE THREAD

**Issue by jeongys1019** [MyPetORG/MyPet#1663]
# Bug report

* [ ] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_A clear and concise description of what the bug is._

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. 
2.
...

## Expected behavior

_A clear and concise description of what you expected to happen._

## Actual behaviour

_If applicable, add screenshots to help explain your problem._

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:**

**MyPet Build/Version:**

**What is the expected result?**

**What happens instead of that?**

**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```
[08:03:00] [Server thread/ERROR]: [MythicMobs] [SCHEDULER] Exception thrown whilst executing task
[08:03:00] [Server thread/WARN]: java.lang.ClassCastException: class de.Keyle.MyPet.compat.v1_20_R3.entity.types.EntityMyAllay cannot be cast to class net.minecraft.world.entity.Display$BlockDisplay (de.Keyle.MyPet.compat.v1_20_R3.entity.types.EntityMyAllay is in unnamed module of loader 'MyPet-3.12-SNAPSHOT-B1756.jar' @84fd537; net.minecraft.world.entity.Display$BlockDisplay is in unnamed module of loader java.net.URLClassLoader @1edf1c96)
[08:03:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.getEntity(CraftEntity.java:106)
[08:03:00] [Server thread/WARN]: 	at net.minecraft.world.entity.Entity.getBukkitEntity(Entity.java:254)
[08:03:00] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityLiving.getBukkitLivingEntity(EntityLiving.java:262)
[08:03:00] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityLiving.knockback(EntityLiving.java:1925)
[08:03:00] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1544)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.core.volatilecode.v1_20_R3.VolatileEntityHandlerImpl.doDamage(VolatileEntityHandlerImpl.java:208)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.bukkit.adapters.BukkitSkillAdapter.doDamage(BukkitSkillAdapter.java:82)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.core.skills.damage.DamagingMechanic.doDamage(DamagingMechanic.java:125)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.core.skills.damage.DamagingMechanic.doDamage(DamagingMechanic.java:90)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.core.skills.mechanics.DamageMechanic.castAtEntity(DamageMechanic.java:48)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.core.skills.SkillMechanic.lambda$executeTargetedEntitySkill$8(SkillMechanic.java:578)
[08:03:00] [Server thread/WARN]: 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.core.skills.SkillMechanic.executeTargetedEntitySkill(SkillMechanic.java:574)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.core.skills.SkillMechanic.lambda$executeSkills$4(SkillMechanic.java:530)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.bukkit.utils.Delegates$RunnableToSupplier.get(Delegates.java:121)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.bukkit.utils.promise.LuminePromise$SupplyRunnable.run(LuminePromise.java:654)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.bukkit.utils.tasks.LumineExecutors$SchedulerWrappedRunnable.run(LumineExecutors.java:70)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.bukkit.utils.promise.LuminePromise.executeSync(LuminePromise.java:133)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.bukkit.utils.promise.LuminePromise.supplySync(LuminePromise.java:264)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.bukkit.utils.promise.Promise.supply(Promise.java:435)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.bukkit.utils.promise.Promise.supplying(Promise.java:104)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.bukkit.utils.tasks.TaskScheduler.run(TaskScheduler.java:63)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.core.skills.SkillMechanic.runMechanic(SkillMechanic.java:565)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.core.skills.SkillMechanic.executeSkills(SkillMechanic.java:530)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.core.skills.SkillMechanic.execute(SkillMechanic.java:447)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.core.skills.MetaSkill.execute(MetaSkill.java:313)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.core.skills.MetaSkill.execute(MetaSkill.java:283)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.core.skills.projectiles.Projectile$ProjectileTracker.close(Projectile.java:709)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.bukkit.utils.terminable.Terminable.closeAndReportException(Terminable.java:61)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.bukkit.utils.terminable.Terminable.terminate(Terminable.java:18)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.core.skills.mechanics.MissileMechanic$MissileTracker.doHit(MissileMechanic.java:424)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.core.skills.mechanics.MissileMechanic$MissileTracker.projectileTick(MissileMechanic.java:378)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.core.skills.projectiles.Projectile$ProjectileTracker.run(Projectile.java:677)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.bukkit.utils.Delegates$RunnableToConsumer.accept(Delegates.java:93)
[08:03:00] [Server thread/WARN]: 	at MythicMobs-5.6.1.jar//io.lumine.mythic.bukkit.utils.Schedulers$LumineTask.run(Schedulers.java:184)
[08:03:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[08:03:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[08:03:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1636)
[08:03:00] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[08:03:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1515)
[08:03:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1216)
[08:03:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[08:03:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Jakllp** [comment]
Update MyPet
