### ISSUE TITLE
Killed Mobs despawn from Pets while throwing Tridents

### ISSUE THREAD

**Issue by MaksyKun** [MyPetORG/MyPet#1665]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate (and I hope I didnt overlook anything).

## Describe the bug

Players seem to encounter despawn behaviour when a Pet kills other mobs with their Trident.

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1.  Use a Pet with a trident + I guess it its the ranged combat tree
2. Let it kill a mob. It has a ~50%/50% Chance to make it despawn
3. The error below appears in console and the mob despawns

[Edit]: It seems like it doesnt even need to have a weapon equipped.

## Expected behavior
The following error and the despawn of a mob that is hit:
```
[21:14:53 ERROR]: Entity threw exception at world_nether:28176.095166385883,67.0,-47450.12492087149
java.lang.ClassCastException: class de.Keyle.MyPet.compat.v1_20_R3.entity.types.EntityMyDrowned cannot be cast to class net.minecraft.world.entity.Display$BlockDisplay (de.Keyle.MyPet.compat.v1_20_R3.entity.types.EntityMyDrowned is in unnamed module of loader 'MyPet-3.12-SNAPSHOT-B1756.jar' @51c27cc0; net.minecraft.world.entity.Display$BlockDisplay is in unnamed module of loader java.net.URLClassLoader @7e32c033)
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.getEntity(CraftEntity.java:122) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.world.entity.Entity.getBukkitEntity(Entity.java:255) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.world.entity.LivingEntity.getBukkitLivingEntity(LivingEntity.java:263) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.knockback(LivingEntity.java:1995) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1600) ~[?:?]
        at net.minecraft.world.entity.Mob.doHurtTarget(Mob.java:1731) ~[?:?]
        at net.minecraft.world.entity.monster.WitherSkeleton.doHurtTarget(WitherSkeleton.java:142) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.checkAndPerformAttack(MeleeAttackGoal.java:130) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.tick(MeleeAttackGoal.java:122) ~[?:?]
        at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:63) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:156) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:147) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:961) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3508) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:707) ~[?:?]
        at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:45) ~[?:?]
        at net.minecraft.world.entity.monster.AbstractSkeleton.aiStep(AbstractSkeleton.java:113) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3157) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:463) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1492) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:940) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:917) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1759) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Bukkit/Spigot/Bungee Build/Version:**  
Current: git-Purpur-2176 (MC: 1.20.4)*
Previous: git-Purpur-2174 (MC: 1.20.4)

**MyPet Build/Version:**
MyPet-3.12-SNAPSHOT-B1756.jar

**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```

**Comment by Jakllp** [comment]
Just update mypet and it should work again ^^
