### ISSUE TITLE
plugin not working on paper 1.20.6

### ISSUE THREAD

**Issue by ScuroK** [MyPetORG/MyPet#1670]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_A clear and concise description of what the bug is._

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. 
2.
...

## Expected behavior

_A clear and concise description of what you expected to happen._

## Actual behaviour

_If applicable, add screenshots to help explain your problem._

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:**
Paper 1.20.6 Build 148
**MyPet Build/Version:**
[3.12-SNAPSHOT-B1760](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1760)
**What is the expected result?**
Plugin shoould work
**What happens instead of that?**
plugin does not work
**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```
[10:58:11] [Server thread/ERROR]: Error occurred while enabling MyPet v3.12 (Is it up to date?)
java.lang.AssertionError: Missing intrusive holder for ResourceKey[minecraft:entity_type / minecraft:mypet_axolotl]:entity.minecraft.pig
	at net.minecraft.core.MappedRegistry.register(MappedRegistry.java:132) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.core.DefaultedMappedRegistry.register(DefaultedMappedRegistry.java:22) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.core.Registry.register(Registry.java:117) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.core.Registry.register(Registry.java:113) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.core.Registry.register(Registry.java:109) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at MyPet-3.12-SNAPSHOT-B1760.jar/de.Keyle.MyPet.compat.v1_20_R4.entity.EntityRegistry.registerEntityType(EntityRegistry.java:69) ~[MyPet-3.12-SNAPSHOT-B1760.jar:?]
	at MyPet-3.12-SNAPSHOT-B1760.jar/de.Keyle.MyPet.compat.v1_20_R4.entity.EntityRegistry.registerEntity(EntityRegistry.java:89) ~[MyPet-3.12-SNAPSHOT-B1760.jar:?]
	at MyPet-3.12-SNAPSHOT-B1760.jar/de.Keyle.MyPet.compat.v1_20_R4.entity.EntityRegistry.registerEntityTypes(EntityRegistry.java:154) ~[MyPet-3.12-SNAPSHOT-B1760.jar:?]
	at MyPet-3.12-SNAPSHOT-B1760.jar/de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:195) ~[MyPet-3.12-SNAPSHOT-B1760.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[10:58:11] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Disabling MyPet v3.12

**Comment by ScuroK** [comment]
server also crashed but i dont know if thats because of mypet:
https://pastebin.com/UFXLq1zn

**Comment by Jakllp** [comment]
Might have something todo with citizens, will have to check

**Comment by Jakllp** [comment]
Confirmed problem when using Citizens

**Comment by Jakllp** [comment]
Forgot to ping this issue in the commit: 2ec7d5e

**Comment by Jakllp** [comment]
Fixed in [3.12-SNAPSHOT-B1761](https://github.com/MyPetORG/MyPet/releases/tag/3.12-SNAPSHOT-B1761)
