### ISSUE TITLE
My pet for Spigot 1.8 Release

### ISSUE THREAD

**Issue by jesusango** [MyPetORG/MyPet#396]
In 1.7.10 it work perfecly, but, with 1.8.1 (spigot new release) it give a error.

Spigot version: [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-"a91cec0"]
MyPet version: 1.2.0

[Server thread/ERROR]: Error occurred while enabling MyPet v1.2.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R4/Packet
    at de.Keyle.MyPet.util.Configuration.setDefault(Configuration.java:175) ~[?:?]
    at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:138) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-"a91cec0"]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:333) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-"a91cec0"]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-"a91cec0"]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:352) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-"a91cec0"]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-"a91cec0"]
    at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:400) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-"a91cec0"]
    at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:368) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-"a91cec0"]
    at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:323) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-"a91cec0"]
    at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-"a91cec0"]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:496) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-"a91cec0"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_20]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R4.Packet
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-"a91cec0"]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-"a91cec0"]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_20]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_20]
    ... 13 more

Can you resolve it, please? Thanks you :)

**Comment by SecretSmoky** [comment]
I have the same Problem :/
